### ISSUE TITLE
fastify-plugin version mismatch error

### ISSUE THREAD

**Issue by MortezaHeydari97** [fastify/fastify-helmet#272]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

5.1.0

### Node.js version

20.18.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Kali 2024.4

### Description

When I'm using `@fastify/helmet` >= 12.x.x in a `nest.js` app, I got the following error:

> .../node_modules/@nestjs/platform-fastify/node_modules/fastify/lib/pluginUtils.js:125
    throw new FST_ERR_PLUGIN_VERSION_MISMATCH(meta.name, requiredVersion, this.version)
          ^
FastifyError [Error]: fastify-plugin: @fastify/helmet - expected '5.x' fastify version, '4.28.1' is installed
    at Object.checkVersion (/home/arthur/projects/api-center/node_modules/@nestjs/platform-fastify/node_modules/fastify/lib/pluginUtils.js:125:11)
    at Object.registerPlugin (/home/arthur/projects/api-center/node_modules/@nestjs/platform-fastify/node_modules/fastify/lib/pluginUtils.js:148:16)
    at Boot.override (/home/arthur/projects/api-center/node_modules/@nestjs/platform-fastify/node_modules/fastify/lib/pluginOverride.js:28:57)
    at Boot._loadPlugin (/home/arthur/projects/api-center/node_modules/@nestjs/platform-fastify/node_modules/avvio/boot.js:425:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'FST_ERR_PLUGIN_VERSION_MISMATCH',
  statusCode: 500
}

> Node.js v20.18.1

But when I try `@fastify/helmet@^11.1.1` the error disappears.

**Comment by mcollina** [comment]
Thanks for reporting. We do not have the resources to support Nest.js users. Please refer to the Nest [Discord](https://discord.gg/NestJS) channel (support) for such questions.
