### ISSUE TITLE
Error: Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by sjorsjes** [fastify/fastify-helmet#38]
I'm using Fastify 1.13.4 and Fastify-helmet 3.0.0. I'm trying to integrate fastify-helmet but even when just using the basis setup used in the tests i recieve the following error:

```
const fastify = require('fastify');
const helmet = require('fastify-helmet');
const app = fastify();

app.register(helmet, { permittedCrossDomainPolicies: true });
```

The error I recieve is the following:
```
<path_to_the_project_dir>\node_modules\fastify\fastify.js:744
    instance._hooks.add(name, fn.bind(instance))
                                 ^

TypeError: Cannot read property 'bind' of undefined
    at _addHook (<path_to_the_project_dir>\node_modules\fastify\fastify.js:744:34)
    at after (<path_to_the_project_dir>\node_modules\fastify\fastify.js:736:9)
    at Object._encapsulateThreeParam (<path_to_the_project_dir>\node_modules\avvio\boot.js:387:7)
    at Boot.callWithCbOrNextTick (<path_to_the_project_dir>\node_modules\avvio\boot.js:311:5)
    at Boot._after (<path_to_the_project_dir>\node_modules\avvio\boot.js:215:26)
    at Plugin.exec (<path_to_the_project_dir>\node_modules\avvio\plugin.js:82:17)
    at Boot.loadPlugin (<path_to_the_project_dir>\node_modules\avvio\plugin.js:166:10)
    at release (<path_to_the_project_dir>\node_modules\fastq\queue.js:127:16)
    at Object.resume (<path_to_the_project_dir>\node_modules\fastq\queue.js:61:7)
    at Plugin.finish (<path_to_the_project_dir>\node_modules\avvio\plugin.js:157:10)
```

**Comment by cemremengu** [comment]
Hello! Can you share a full example? Do you get this error as soon as you register the plugin?

**Comment by sjorsjes** [comment]
Hi, i'm sorry but i am not able to reproduce the error. Must have been a "hey mate it's friday and let it go" bug...
